######################################################
######   CDP TECHNICAL TASK - ISABELLA MORGANTE ######
######################################################

# Set working directory
setwd("~/Documents/CDP_Task/Code/")
rm(list=ls(all=TRUE))
graphics.off()

# Packages
require(ggplot2)
require(dplyr)
library(rvest)

# Load data 
cdp_data <- read.csv(file = "../Data/Electricity generation by source - top 5.csv", header = TRUE)

# Explore data 
head(cdp_data) #first few rows
str(cdp_data) #structure


# Change column name to avoid dots
names(which(colSums(is.na(cdp_data))>0)) # List columns containing NAs

# Change column name to avoid dots and remove NAs
cdp_data <- rename(cdp_data, ElectricityGeneration_GWh = Electricity.Generation..GWh.) %>% replace(is.na(.), 0)

################################################################################
## QUESTION 1
## Calculate the total electricity generation per year. How does this change overtime?
################################################################################

total_electricity <- cdp_data  %>%
  group_by(Year, Country) %>%
  summarise(Total_ElectricityGeneration_GWh = sum(ElectricityGeneration_GWh))

p_country_totals <- ggplot(filter(total_electricity, Country!='World'), aes(x = Year, y = Total_ElectricityGeneration_GWh, fill = Country)) + 
  geom_point(aes(color=Country)) +
  geom_line(aes(color=Country))+ 
  theme_bw() + 
  ylab("Electricity Generation [GWh]") +
  ggtitle("Total Electricity Generation by Country")

p_country_totals
################################################################################
## QUESTION 2
## What percentage of electricity is generated from fossil fuel sources per year?
################################################################################

FF_electricity <- filter(cdp_data, Source == "Coal"| Source =="Natural gas" | Source == "Oil") %>% # filter by fossil fuel
  group_by(Year, Country) %>% 
  summarise(FossilFuel_ElectricityGeneration_GWh = sum(ElectricityGeneration_GWh)) # sum generation values from all sources

FF_Total <- full_join(FF_electricity, total_electricity, by = c('Year', 'Country')) %>% # join total generation with fossil fuel generation
  mutate(
    Percent_FF = FossilFuel_ElectricityGeneration_GWh / Total_ElectricityGeneration_GWh * 100 # calculate percentage 
  )

p_FF_percent <- ggplot(filter(FF_Total, Country!='World'), aes(x = Year, y = Percent_FF, fill = Country)) + 
  geom_point(aes(color=Country)) +
  geom_line(aes(color=Country))+ 
  theme_bw() +
  ylab("Percentage") +
  ggtitle("Percentage of Electricity Generated by Fossil Fuels")

p_FF_percent

################################################################################
## QUESTION 3
## For the most recent year, what percentage of world coal generation do the top five countries represent? How does this compare to natural gas?
################################################################################
# Plot trends for oil and gas generation by China and World
p <- ggplot(filter(cdp_data, Source == "Coal"| Source == "Natural gas", Country == "World" | Country == "China" ), aes(x = Year, y = ElectricityGeneration_GWh, fill = Source)) + 
  geom_point(aes(color=Country)) +
  geom_line(aes(color=Country, linetype = Source))+ 
  theme_bw() +
  ylab("Electricity Generation GWh") 
p

# All increasing choose models to fit -- quadratic lm, glm with gaussian log link
# Select model with lowest AIC score to make prediction for 2019 value 
cg_2019 <- filter(cdp_data, Source == "Coal" | Source=="Natural gas", Year == 2019)

for (country in c("China", "World")){
  for (source in c("Coal", "Natural gas")){
    data2Fit <- filter(cdp_data, Source == source, Country == country)
    
    # Fit models
    QuadFit <- lm(ElectricityGeneration_GWh ~ poly(Year,2), data = data2Fit)
    CubFit <- lm(ElectricityGeneration_GWh ~ poly(Year,3), data = data2Fit)
    ExpFit <- lm(log(ElectricityGeneration_GWh) ~ log(Year), data = data2Fit)
    GLMFit <- glm(ElectricityGeneration_GWh ~ log(Year), data = data2Fit, family = gaussian(link = "log"))
    #NLS_Fit <- nlsLM(ElectricityGeneration_GWh ~ a * Year^b, data = data2Fit, start = list(a = exp(coef(ExpFit)[1]), b = coef(ExpFit)[2])) # Need better starting values
    
    # Plot the model fits
    plot(ElectricityGeneration_GWh ~ Year, data = data2Fit)
    curve(predict(QuadFit, newdata = data.frame(Year = x)), col = "black", add = TRUE)
    curve(predict(CubFit, newdata = data.frame(Year = x)), col = "orange", add = TRUE)
    curve(exp(predict(ExpFit, newdata = data.frame(Year = x))), col = "blue", add = TRUE)
    curve(predict(GLMFit, newdata = data.frame(Year = x), type = "response"), col = "red", add = TRUE)
    #curve(predict(NLS_Fit, newdata = data.frame(Year = x)), col = "green", add = TRUE)
    legend("topleft", legend = c("Quadratic", "Cubic", "Exponential", "Gauss GLM"),
           col = c("black", "orange", "blue", "red"),
           lty = c(1, 1, 1))
    
    # Find AIC for models and their predicted value for 2019
    AIC_values <- data.frame(Model  = c("QuadFit", "CubFit", "ExpFit", "GLMFit"), AIC = c(AIC(QuadFit), AIC(CubFit), AIC(ExpFit), AIC(GLMFit)), Prediction = c(as.numeric(predict(QuadFit, data.frame(Year = 2019))), as.numeric(predict(CubFit, data.frame(Year = 2019))), as.numeric(exp(predict(ExpFit, data.frame(Year = 2019)))), as.numeric(predict(GLMFit, data.frame(Year = 2019), type = "response"))))
    
    # Select best fitting model by minimum AIC value 
    best_fit <- AIC_values[which.min(AIC_values$AIC), ]
    
    
    cg_2019 <- cg_2019 %>% add_row(Year = 2019, Country = country, Units = "GWh", Source = source, ElectricityGeneration_GWh = best_fit$Prediction)
  }
}

## Extrapolation method 
coal_gas_2019 <- filter(cdp_data, Source == "Coal" | Source=="Natural gas", Year == 2019)
coal_gas_extrap <- filter(cdp_data, Source == "Coal" | Source=="Natural gas", Country == "World" | Country == "China", Year > 2014)

for (country in unique(coal_gas_extrap$Country)){
  for (source in unique(coal_gas_extrap$Source)){
    d <- filter(coal_gas_extrap, Source == source, Country == country)
    model <- lm(ElectricityGeneration_GWh ~ Year, data = d)
    elec_gen_19 <- as.numeric(predict(model, data.frame(Year = 2019)))
 
    coal_gas_2019 <- coal_gas_2019 %>% add_row(Year = 2019, Country = country, Units = "GWh", Source = source, ElectricityGeneration_GWh = elec_gen_19)
  }
}

coal_gas_sums_2019 <- filter(coal_gas_2019, Country != "World") %>%
  group_by(Year, Source) %>%
  summarise(ElectricityGeneration_GWh = sum(ElectricityGeneration_GWh)) 
  
percent_coal_2019 <- filter(coal_gas_sums_2019, Source == "Coal") %>% pull(ElectricityGeneration_GWh) / filter(coal_gas_2019, Source == "Coal", Country == "World") %>% pull(ElectricityGeneration_GWh)

percent_gas_2019 <- filter(coal_gas_sums_2019, Source == "Natural gas") %>% pull(ElectricityGeneration_GWh) / filter(coal_gas_2019, Source == "Natural gas", Country == "World") %>% pull(ElectricityGeneration_GWh)


###############################################################
## Historic Coal and Oil usage
###############################################################

# Sum electricity generation by coal and gas for all countries
coal_gas_country <- filter(cdp_data, Source == "Coal" & Country != "World" | Source == "Natural gas" & Country != "World") %>%
  group_by(Year, Source) %>%
  summarise(ElectricityGeneration_GWh_TopFive = sum(ElectricityGeneration_GWh))

# Global coal and gas 
coal_gas_global <- filter(cdp_data, Source == "Coal" & Country == "World" | Source == "Natural gas" & Country == "World")

# Divide country generation by gloabl value to get proportion and join into single df
coal_gas <- full_join(coal_gas_country, coal_gas_global, by = c('Year','Source')) %>%
  group_by(Year, Source) %>%
  mutate(
    Percent = ElectricityGeneration_GWh_TopFive / ElectricityGeneration_GWh
  )

# Plot changes until 2015
coal_gas_2015 <- filter(coal_gas, Year < 2018)
p_coal_gas_changes_2015 <- ggplot(coal_gas_2015, aes(x = Year, y = Percent, fill = Source)) + 
  geom_point(aes(color=Source)) +
  geom_line(aes(color=Source))+ 
  theme_bw() +
  ylab("Electricity Generation [GWh]") 

p_coal_gas_changes_2015

################################################################################
## QUESTION 4
## Using data from the previous exercise with the table you have just extracted, calculate the total GHG lifecycle emissions per year for a country of your choice using the equation
################################################################################

## Extract data ‘Lifecycle greenhouse gas emissions by electricity source’ table
url <- "https://en.wikipedia.org/wiki/Emission_intensity"
table_XPath <- '//*[@id="mw-content-text"]/div[1]/table[1]'

lifecycle_GHG_emissions <- url %>%
  read_html() %>%
  html_nodes(xpath=table_XPath) %>%
  html_table()
lifecycle_GHG_emissions <-lifecycle_GHG_emissions[[1]]
lifecycle_GHG_emissions <- rename(lifecycle_GHG_emissions, Source = Technology, GHG_EF = `50th percentile  (g CO2-eq/kWhe)`)

## View lifecycle GHG data
head(lifecycle_GHG_emissions)
str(lifecycle_GHG_emissions)

## Add GHG values to cdp data to find emissions
emissions <- full_join(cdp_data, lifecycle_GHG_emissions, by = c('Source')) %>% na.omit() %>% # Nas will be produced from countries not generating electricity by a certain source one year and any additional Sources that were included in the wiki data (i.e. didn't match).
  mutate(
    ElectricityGeneration_kWh = ElectricityGeneration_GWh * 1e6, #Convert from GWh to kWh
    GHG_Emissions = ElectricityGeneration_kWh * GHG_EF # Calculate emissions
  )
        
  
total_emissions <- emissions %>%
  group_by(Year, Country) %>%
  summarise(Total_GHG_Emissions = sum(GHG_Emissions))

### Plot 
p_GHG_emissions <- ggplot(total_emissions, aes(x = Year, y = Total_GHG_Emissions, fill = Country)) + 
  geom_point(aes(color=Country)) +
  geom_line(aes(color=Country))+ 
  theme_bw() +
  ylab("GHG Emissions") 

p_GHG_emissions

################################################################################
################################################################################

