######################################################
######   CDP TECHNICAL TASK - ISABELLA MORGANTE ######
######################################################

# Set working directory
setwd("~/Documents/CDP_Task/Code/")
rm(list=ls(all=TRUE))
graphics.off()

# Packages
require(ggplot2)
require(dplyr)
library(rvest)

# Load data 
cdp_data <- read.csv(file = "../Data/Electricity generation by source - top 5.csv", header = TRUE)

# Explore data 
head(cdp_data) #first few rows
str(cdp_data) #structure

# add info about dealing with NAs and checking consistent units
## Check similarities in text etc. -- cleaning for typos blah blah 

# Change column name to avoid dots
names(cdp_data)[names(cdp_data) == "Electricity.Generation..GWh."] <- "ElectricityGeneration_GWh"


################################################################################
## QUESTION 1
## Calculate the total electricity generation per year. How does this change overtime?
################################################################################

# Sum  all source electricity for each country
total_electricity <- aggregate(cdp_data$ElectricityGeneration_GWh, by=list(Year = cdp_data$Year, Country = cdp_data$Country),FUN=sum, na.rm=TRUE) 
names(total_electricity)[names(total_electricity) == "x"] <- "ElectricityGeneration_GWh"
country_total_electricity <- total_electricity[!total_electricity$Country=='World',] # ignore world values

p_country_totals <- ggplot(country_total_electricity, aes(x = Year, y = ElectricityGeneration_GWh, fill = Country)) + 
  geom_point(aes(color=Country)) +
  geom_line(aes(color=Country))+ 
  theme_bw() +
  ylab("Total Electricity Generation [GWh]") 

p_country_totals

p_global_totals <- ggplot(total_electricity[total_electricity$Country=='World',], aes(x = Year, y = ElectricityGeneration_GWh, fill = Country)) + 
  geom_point(aes(color=Country)) +
  geom_line(aes(color=Country))+ 
  theme_bw() +
  ylab("Total Electricity Generation [GWh]") 

p_global_totals
################################################################################
## QUESTION 2
## What percentage of electricity is generated from fossil fuel sources per year?
################################################################################

# Choose country to explore
country <- "China"
country_data <- subset(cdp_data, cdp_data$Country == country) # Subset data by contry of interest
country_data <- na.omit(country_data) # remove NAs 

# Plot different sources over time
p_sources <- ggplot(country_data, aes(x = Year, y = ElectricityGeneration_GWh, fill = Source)) + 
  geom_point(aes(color=Source)) +
  geom_line(aes(color=Source))+ 
  theme_bw() +
  ylab("Electricity Generation [GWh]") 

p_sources

# Combine fossil fuels 
FF_electricity <- subset(country_data, country_data$Source == "Coal" | country_data$Source == "Natural gas" | country_data$Source == "Oil")
####FF <- filter(country_data, Source == "Coal" | Source == "Natural gas" | Source == "Oil")
FF_electricity <- aggregate(FF_electricity$ElectricityGeneration_GWh, by=list(Year = FF_electricity$Year), FUN=sum, na.rm=TRUE) 
names(FF_electricity)[names(FF_electricity) == "x"] <- "ElectricityGeneration_GWh"
FF_electricity$Source <- "Fossil Fuel"

# Find FF as a percentage of total generation
country_total <- subset(total_electricity, total_electricity$Country == country)
country_total$Country <- NULL
country_total$Source <- "Total"

# Combine FF and Total
FF_totals <- rbind(country_total, FF_electricity)
percent_FF <- data.frame(matrix(ncol=2,nrow=length(unique(FF_totals$Year)), dimnames=list(NULL, c("Year", "Percentage"))))
count <- 1
for (i in unique(FF_totals$Year)){
  df <- subset(FF_totals, FF_totals$Year == i)
  percent <- df[df$Source == "Fossil Fuel", "ElectricityGeneration_GWh"] / df[df$Source == "Total", "ElectricityGeneration_GWh"]
  
  percent_FF$Year[count] <- i
  percent_FF$Percentage[count] <- percent * 100
  
  count = count + 1
}

# Plot 
p_china_FF <- ggplot(percent_FF, aes(x = Year, y = Percentage)) + 
  geom_point() +
  geom_line()+ 
  theme_bw() +
  ylab("Percentage of electricity generated by fossil fuels in China") 

p_china_FF
  
  
  
## FF vs Other sources
# Combine other sources
other_electricity <- subset(country_data, country_data$Source != "Coal" & country_data$Source != "Natural gas" & country_data$Source != "Oil")
other_electricity <- aggregate(other_electricity$ElectricityGeneration_GWh, by=list(Year = other_electricity$Year), FUN=sum, na.rm=TRUE) 
names(other_electricity)[names(other_electricity) == "x"] <- "ElectricityGeneration_GWh"
other_electricity$Source <- "Other Energy Source"

# Combine all dfs
FF_other_electricity <- rbind(FF_electricity, other_electricity)

# Plot 
p_FF_other <- ggplot(FF_other_electricity, aes(x = Year, y = ElectricityGeneration_GWh, fill = Source)) + 
  geom_point(aes(color=Source)) +
  geom_line(aes(color=Source))+ 
  theme_bw() +
  ylab("Electricity Generation [GWh]") 

p_FF_other

# total, FF and other 


################################################################################
## QUESTION 3
## For the most recent year, what percentage of world coal generation do the top five countries represent? How does this compare to natural gas?
################################################################################

# Combine coal generation  
coal_electricity <- subset(cdp_data, cdp_data$Source == "Coal" & cdp_data$Country != "World")
coal_electricity <- aggregate(coal_electricity$ElectricityGeneration_GWh, by=list(Year = coal_electricity$Year), FUN=sum, na.rm=TRUE) 
names(coal_electricity)[names(coal_electricity) == "x"] <- "ElectricityGeneration_GWh"

# Add together 2019 and 2018 data 
coal_electricity[coal_electricity$Year == 2018, "ElectricityGeneration_GWh"] <- coal_electricity[coal_electricity$Year == 2018, "ElectricityGeneration_GWh"] + coal_electricity[coal_electricity$Year == 2019, "ElectricityGeneration_GWh"]
# Remove 2019 row
coal_electricity <- coal_electricity[coal_electricity$Year != 2019, ]

# Empty data frame to store percentages 
percent_coal <- data.frame(matrix(ncol=2,nrow=length(unique(coal_electricity$Year)), dimnames=list(NULL, c("Year", "Percentage"))))
count <- 1

for (i in unique(coal_electricity$Year)){
  percent <- coal_electricity[coal_electricity$Year == i, "ElectricityGeneration_GWh"] / cdp_data[cdp_data$Country == "World" & cdp_data$Source == "Coal" & cdp_data$Year == i, "ElectricityGeneration_GWh"]
  
  percent_coal$Year[count] <- i
  percent_coal$Percentage[count] <- percent
  
  count = count + 1
}

p_coal_percent <- ggplot(percent_coal, aes(x = Year, y = Percentage)) + 
  geom_point() +
  geom_line()+ 
  theme_bw() +
  ylab("Proportion of coal electricity generated by top five") 

p_coal_percent




# Combine coal generation  
gas_electricity <- subset(cdp_data, cdp_data$Source == "Natural gas" & cdp_data$Country != "World")
gas_electricity <- aggregate(gas_electricity$ElectricityGeneration_GWh, by=list(Year = gas_electricity$Year), FUN=sum, na.rm=TRUE) 
names(gas_electricity)[names(gas_electricity) == "x"] <- "ElectricityGeneration_GWh"

# Add together 2019 and 2018 data 
gas_electricity[gas_electricity$Year == 2018, "ElectricityGeneration_GWh"] <- gas_electricity[gas_electricity$Year == 2018, "ElectricityGeneration_GWh"] + gas_electricity[gas_electricity$Year == 2019, "ElectricityGeneration_GWh"]
# Remove 2019 row
gas_electricity <- gas_electricity[gas_electricity$Year != 2019, ]

# Empty data frame to store percentages 
percent_gas <- data.frame(matrix(ncol=2,nrow=length(unique(gas_electricity$Year)), dimnames=list(NULL, c("Year", "Percentage"))))
count <- 1

for (i in unique(gas_electricity$Year)){
  percent <- gas_electricity[gas_electricity$Year == i, "ElectricityGeneration_GWh"] / cdp_data[cdp_data$Country == "World" & cdp_data$Source == "Coal" & cdp_data$Year == i, "ElectricityGeneration_GWh"]
  
  percent_gas$Year[count] <- i
  percent_gas$Percentage[count] <- percent
  
  count = count + 1
}

p_gas_percent <- ggplot(percent_gas, aes(x = Year, y = Percentage)) + 
  geom_point() +
  geom_line()+ 
  theme_bw() +
  ylab("Proportion of coal electricity generated by top five") 

p_gas_percent




# Combine coal generation  
coal_gas_electricity <- subset(cdp_data, cdp_data$Source == "Coal" | cdp_data$Source == "Natural gas")




coal_electricity <- aggregate(coal_electricity$ElectricityGeneration_GWh, by=list(Year = coal_electricity$Year), FUN=sum, na.rm=TRUE) 
names(coal_electricity)[names(coal_electricity) == "x"] <- "ElectricityGeneration_GWh"

# Add together 2019 and 2018 data 
coal_electricity[coal_electricity$Year == 2018, "ElectricityGeneration_GWh"] <- coal_electricity[coal_electricity$Year == 2018, "ElectricityGeneration_GWh"] + coal_electricity[coal_electricity$Year == 2019, "ElectricityGeneration_GWh"]
# Remove 2019 row
coal_electricity <- coal_electricity[coal_electricity$Year != 2019, ]

# Empty data frame to store percentages 
percent_coal <- data.frame(matrix(ncol=2,nrow=length(unique(coal_electricity$Year)), dimnames=list(NULL, c("Year", "Percentage"))))
count <- 1

for (i in unique(coal_electricity$Year)){
  percent <- coal_electricity[coal_electricity$Year == i, "ElectricityGeneration_GWh"] / cdp_data[cdp_data$Country == "World" & cdp_data$Source == "Coal" & cdp_data$Year == i, "ElectricityGeneration_GWh"]
  
  percent_coal$Year[count] <- i
  percent_coal$Percentage[count] <- percent
  
  count = count + 1
}












################################################################################
## QUESTION 4
## Using data from the previous exercise with the table you have just extracted, calculate the total GHG lifecycle emissions per year for a country of your choice using the equation
################################################################################

## Extract data ‘Lifecycle greenhouse gas emissions by electricity source’ table
url <- "https://en.wikipedia.org/wiki/Emission_intensity"
table_XPath <- '//*[@id="mw-content-text"]/div[1]/table[1]'

lifecycle_GHG_emissions <- url %>%
  read_html() %>%
  html_nodes(xpath=table_XPath) %>%
  html_table()
lifecycle_GHG_emissions <-lifecycle_GHG_emissions[[1]]












